Repository apache/maven, pull requests merged in 2025-03, with the labels that each got.

#2146 [MNG-8611] Build with apache-release profile
  .github/workflows/maven.yml
  compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/DefaultToolchainsBuilder.java
  compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/DefaultToolchainsBuildingRequest.java
  compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/DefaultToolchainsBuildingResult.java
  compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/ToolchainsBuilder.java
  compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/ToolchainsBuildingException.java
  compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/ToolchainsBuildingRequest.java
  compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/building/ToolchainsBuildingResult.java
  compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/io/ToolchainsReader.java
  compat/maven-toolchain-builder/src/main/java/org/apache/maven/toolchain/io/ToolchainsWriter.java
Labels: maintenance

#2177 Use Maven 3.9.9 for build maven-3.9.x branch
  .github/workflows/maven.yml
  Jenkinsfile
Labels: mvn3, maintenance

#2171 [MNG-8248] Add enable-native-access to startup scripts
  apache-maven/src/bin/mvn
  apache-maven/src/bin/mvn.cmd
Labels: mvn3

#2178 Remove old symbolic link in ITmng8400 test
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8400CanonicalMavenHomeTest.java
Labels: maintenance
