Repository apache/maven, pull requests merged in 2025-06, with the labels that each got.

#2419 [MNG-8763] Remove name from site bannerLeft
  src/site/site.xml
Labels: mvn3

#2431 [MNG-8767] Add suppressed exceptions to BatchRequestException in AbstractRequestCache
  impl/maven-impl/src/main/java/org/apache/maven/impl/cache/AbstractRequestCache.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/cache/AbstractRequestCacheTest.java
Labels: bug

#2380 Maven4 "legacy" mode and more
  api/maven-api-core/src/main/java/org/apache/maven/api/Constants.java
  api/maven-api-core/src/main/java/org/apache/maven/api/feature/Features.java
  api/maven-api-core/src/main/java/org/apache/maven/api/services/ModelBuilder.java
  compat/maven-compat/src/test/java/org/apache/maven/project/AbstractMavenProjectTestCase.java
  impl/maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java
  impl/maven-core/src/main/java/org/apache/maven/internal/aether/MavenTransformer.java
  impl/maven-core/src/main/java/org/apache/maven/internal/transformation/PomArtifactTransformer.java
  impl/maven-core/src/main/java/org/apache/maven/internal/transformation/TransformerManager.java
  impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/ConsumerPomArtifactTransformer.java
  impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultConsumerPomBuilder.java
  impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultTransformerManager.java
  impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/PomBuilder.java
  impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/PomInlinerTransformer.java
  impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/TransformedArtifact.java
  impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/TransformerSupport.java
  impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleModuleBuilder.java
  impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/concurrent/BuildPlanExecutor.java
  impl/maven-core/src/test/java/org/apache/maven/AbstractCoreMavenComponentTestCase.java
  impl/maven-core/src/test/java/org/apache/maven/MavenTestHelper.java
  impl/maven-core/src/test/java/org/apache/maven/internal/impl/TestApi.java
  impl/maven-core/src/test/java/org/apache/maven/internal/transformation/impl/ConsumerPomArtifactTransformerTest.java
  impl/maven-core/src/test/java/org/apache/maven/internal/transformation/impl/ConsumerPomBuilderTest.java
  impl/maven-impl/src/main/java/org/apache/maven/api/services/model/ModelValidator.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelValidator.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/resolver/MavenSessionBuilderSupplier.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/resolver/scopes/Maven3ScopeManagerConfiguration.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/model/DefaultModelValidatorTest.java
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8744CIFriendlyTest.java
  its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
  its/core-it-suite/src/test/resources/mng-8744-ci-friendly/.mvn/.gitkeep
  its/core-it-suite/src/test/resources/mng-8744-ci-friendly/module-1/pom.xml
  its/core-it-suite/src/test/resources/mng-8744-ci-friendly/module-2/pom.xml
  its/core-it-suite/src/test/resources/mng-8744-ci-friendly/module-3/jar-with-prod.xml
  its/core-it-suite/src/test/resources/mng-8744-ci-friendly/module-3/pom.xml
  its/core-it-suite/src/test/resources/mng-8744-ci-friendly/pom.xml
  src/site/markdown/configuration.properties
  src/site/markdown/configuration.yaml
  src/site/markdown/maven-configuration.md
Labels: enhancement

#2447 Improve configuration for dependabot in 3.x branch
  .github/dependabot.yml
Labels: build

#2378 [MNG-8736] Fix concurrency issue in model building with profile activation
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultProfileActivationContext.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/MavenModelMerger.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/model/MavenModelMergerTest.java
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8736ConcurrentFileActivationTest.java
  its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
  its/core-it-suite/src/test/resources/mng-8736/child1/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child1/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child10/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child11/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child11/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child12/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child13/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child13/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child14/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child15/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child15/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child16/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child17/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child17/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child18/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child19/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child19/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child2/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child20/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child21/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child21/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child22/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child23/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child23/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child24/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child25/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child25/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child26/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child27/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child27/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child28/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child29/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child29/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child3/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child3/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child30/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child31/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child31/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child32/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child4/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child5/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child5/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child6/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child7/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child7/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child8/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/child9/activate.marker
  its/core-it-suite/src/test/resources/mng-8736/child9/pom.xml
  its/core-it-suite/src/test/resources/mng-8736/pom.xml
Labels: bug

#2449 Update CONTRIBUTING after GitHub issues enabled
  CONTRIBUTING.md
Labels: mvn3, maintenance

#2435 Don't ignore SVG files
  .gitignore
Labels: maintenance

#2436 Refactor WrapperProperties template to remove caching and simplify implementation
  impl/maven-core/src/test/java/org/apache/maven/model/PropertiesOrderTest.java
  impl/maven-core/src/test/java/org/apache/maven/model/PropertiesTest.java
  impl/maven-core/src/test/java/org/apache/maven/model/WrapperPropertiesOrderTest.java
  src/mdo/java/WrapperProperties.java
Labels: maintenance

#2474 Move project mutation inside project lock
  impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoExecutor.java
Labels: bug

#2480 User properties are not interpolated for paths
  impl/maven-cli/pom.xml
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/CommonsCliOptions.java
  impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/BaseParserTest.java
  impl/maven-cli/src/test/resources/mavenHome/conf/maven.properties
  impl/maven-cli/src/test/resources/userHome/.m2/maven.properties
  impl/maven-cli/src/test/resources/userHome/.m2/settings.xml
Labels: bug

#2493 Deduplicate filtered dependency graph
  impl/maven-core/src/main/java/org/apache/maven/graph/FilteredProjectDependencyGraph.java
  impl/maven-core/src/test/java/org/apache/maven/graph/DefaultProjectDependencyGraphTest.java
  pom.xml
Labels: bug

#2504 Execute GitHub action - Java CI on maven-4.0.x branch
  .github/workflows/maven.yml
Labels: maintenance

#2505 Add quotes in the command-line arguments formatted by `JavaPathType`.
  api/maven-api-core/src/main/java/org/apache/maven/api/Artifact.java
  api/maven-api-core/src/main/java/org/apache/maven/api/ArtifactCoordinates.java
  api/maven-api-core/src/main/java/org/apache/maven/api/Dependency.java
  api/maven-api-core/src/main/java/org/apache/maven/api/DownloadedArtifact.java
  api/maven-api-core/src/main/java/org/apache/maven/api/JavaPathType.java
  api/maven-api-core/src/main/java/org/apache/maven/api/SourceRoot.java
  api/maven-api-core/src/test/java/org/apache/maven/api/JavaPathTypeTest.java
Labels: bug

#2503 Update branch name for release-drafter in maven-4.0.x
  .github/workflows/release-drafter.yml
Labels: maintenance

#2513 Update Maven version to 4.0.0-SNAPSHOT
  apache-maven/pom.xml
  api/maven-api-annotations/pom.xml
  api/maven-api-cli/pom.xml
  api/maven-api-core/pom.xml
  api/maven-api-di/pom.xml
  api/maven-api-metadata/pom.xml
  api/maven-api-model/pom.xml
  api/maven-api-plugin/pom.xml
  api/maven-api-settings/pom.xml
  api/maven-api-spi/pom.xml
  api/maven-api-toolchain/pom.xml
  api/maven-api-xml/pom.xml
  api/pom.xml
  compat/maven-artifact/pom.xml
  compat/maven-builder-support/pom.xml
  compat/maven-compat/pom.xml
  compat/maven-embedder/pom.xml
  compat/maven-model-builder/pom.xml
  compat/maven-model/pom.xml
  compat/maven-plugin-api/pom.xml
  compat/maven-repository-metadata/pom.xml
  compat/maven-resolver-provider/pom.xml
  compat/maven-settings-builder/pom.xml
  compat/maven-settings/pom.xml
  compat/maven-toolchain-builder/pom.xml
  compat/maven-toolchain-model/pom.xml
  compat/pom.xml
  impl/maven-cli/pom.xml
  impl/maven-core/pom.xml
  impl/maven-di/pom.xml
  impl/maven-executor/pom.xml
  impl/maven-impl/pom.xml
  impl/maven-jline/pom.xml
  impl/maven-logging/pom.xml
  impl/maven-support/pom.xml
  impl/maven-testing/pom.xml
  impl/maven-xml/pom.xml
  impl/pom.xml
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng3991ValidDependencyScopeTest.java
  its/pom.xml
  pom.xml
Labels: chore
