Repository apache/maven, pull requests merged in 2025-10, with the labels that each got.

#11148 Move documentation of Maven Mixins to site
  src/site/markdown/mixins.md
  src/site/site.xml
Labels: skip-changelog

#11092 Fix #10939: DefaultModelXmlFactory: make location tracking opt-in—disabled by def…
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultModelXmlFactoryTest.java
Labels: bug, backport-to-4.0.x

#11197 Simplify prefix resolution
  maven-core/src/main/java/org/apache/maven/plugin/prefix/internal/DefaultPluginPrefixResolver.java
Labels: mvn3, enhancement

#11213 [maven-4.0.x] Improve mvn usage message (#11211)
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/CommonsCliOptions.java
Labels: bug, backport

#11216 GH-11181 Metaversion validation and lax conflict detection (#11184)
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/PrecedenceCoreExtensionSelector.java
  impl/maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultPluginDependenciesResolver.java
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh11181CoreExtensionsMetaVersionsTest.java
  its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/pw-metaversion-is-invalid/.mvn/extensions.xml
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/pw-metaversion-is-invalid/HOME/.placeholder
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/pw-metaversion-is-invalid/pom.xml
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-metaversion-is-valid/.mvn/.placeholder
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-metaversion-is-valid/HOME/.m2/extensions.xml
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-metaversion-is-valid/pom.xml
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-different-version-is-conflict/.mvn/extensions.xml
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-different-version-is-conflict/HOME/.m2/extensions.xml
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-different-version-is-conflict/pom.xml
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-same-version-is-not-conflict/.mvn/extensions.xml
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-same-version-is-not-conflict/HOME/.m2/extensions.xml
  its/core-it-suite/src/test/resources/gh-11181-core-extensions-meta-versions/uw-pw-same-version-is-not-conflict/pom.xml
Labels: backport

#11217 IT fixes
  its/core-it-suite/pom.xml
Labels: backport

#11222 Rename cache keys
  .github/workflows/maven.yml
Labels: maintenance
