Repository apache/maven, pull requests merged in 2025-07, with the labels that each got.

#2522 Add automated porting system between maven-4.0.x and master branches
  .github/AUTO_PORT.md
  .github/workflows/auto-port.yml
Labels: enhancement, maintenance

#2536 [maven-4.0.x] Fix ReactorReader incorrect warnings and logic (fixes #2497, #2498)
  impl/maven-core/src/main/java/org/apache/maven/ReactorReader.java
Labels: bug, backport

#2554 bug: fix duplicate dependency in effective model (fixes #2532)
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh2532DuplicateDependencyEffectiveModelTest.java
  its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
  its/core-it-suite/src/test/resources/gh-2532-duplicate-dependency-effective-model/module-a/pom.xml
  its/core-it-suite/src/test/resources/gh-2532-duplicate-dependency-effective-model/pom.xml
Labels: bug, backport-to-4.0.x

#2547 Split system and user properties from maven.properties
  apache-maven/src/assembly/maven/conf/maven-system.properties
  apache-maven/src/assembly/maven/conf/maven-user.properties
  api/maven-api-annotations/src/main/java/org/apache/maven/api/annotations/Config.java
  api/maven-api-core/src/main/java/org/apache/maven/api/ProtoSession.java
  api/maven-api-core/src/main/java/org/apache/maven/api/Session.java
  compat/maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
  compat/maven-embedder/src/test/java/org/apache/maven/cli/MavenCliTest.java
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/BaseParser.java
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/LookupInvoker.java
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/PlexusContainerCapsuleFactory.java
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvn/MavenInvoker.java
  impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/BaseParserTest.java
  impl/maven-cli/src/test/resources/mavenHome/conf/maven-system.properties
  impl/maven-cli/src/test/resources/mavenHome/conf/maven-user.properties
  impl/maven-cli/src/test/resources/userHome/.m2/maven-user.properties
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSettingsBuilder.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
  src/site/markdown/configuring.md
Labels: bug, mvn40

#2555 [maven-4.0.x] Switch to rwlock-local (#2546)
  impl/maven-cli/src/test/resources/mavenHome/conf/maven-system.properties
Labels: performance

#2567 Cleanups duplicate configs with new parent
  pom.xml
Labels: maintenance, mvn40

#2570 chore: remove unused managed dependency
  pom.xml
Labels: maintenance, backport-to-4.0.x

#2572 [maven-4.0.x] chore: remove unused managed dependency (#2570)
  pom.xml
Labels: maintenance, backport, mvn40

#2573 [maven-4.0.x] Fix MavenProject#getPlugin(String) performances (#2530)
  impl/maven-core/src/main/java/org/apache/maven/project/MavenProject.java
  impl/maven-core/src/test/java/org/apache/maven/project/PluginConnectionSimpleTest.java
Labels: backport, performance, mvn40

#2575 Augment version range resolution used repositories
  api/maven-api-core/src/main/java/org/apache/maven/api/Constants.java
  compat/maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/DefaultVersionRangeResolver.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/resolver/DefaultVersionRangeResolver.java
  src/site/markdown/configuration.properties
  src/site/markdown/configuration.yaml
  src/site/markdown/maven-configuration.md
Labels: enhancement

#10896 Build the project by JDK 21 as default
  .github/workflows/maven.yml
  Jenkinsfile
  maven-core/src/test/java/org/apache/maven/graph/DefaultProjectDependencyGraphTest.java
Labels: mvn3, build

#10897 Pin GitHub action versions by hash
  .github/workflows/maven.yml
Labels: build

#10907 Use local repository as tail in MavenExecutorTest
  impl/maven-executor/src/test/java/org/apache/maven/cling/executor/MavenExecutorTestSupport.java
Labels: skip-changelog

#10901 Refactor setupContainer to validate ExtensionContext, test class and instance, and throw clear IllegalStateExceptions (fixes #10428)
  impl/maven-testing/src/main/java/org/apache/maven/api/di/testing/MavenDIExtension.java
  impl/maven-testing/src/test/java/org/apache/maven/api/di/testing/SimpleDITest.java
Labels: bug, backport-to-4.0.x

#10912 Bug fix in the default directory computed by `DefaultSourceRoot`.
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultSourceRootTest.java
Labels: bug, backport-to-4.0.x

#2527 Optimize XmlPlexusConfiguration for performance and thread safety
  impl/maven-xml/BENCHMARKS.md
  impl/maven-xml/pom.xml
  impl/maven-xml/src/main/java/org/apache/maven/internal/xml/XmlPlexusConfiguration.java
  impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationBenchmark.java
  impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationConcurrencyBenchmark.java
  impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationMemoryBenchmark.java
  impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationOld.java
  impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationTest.java
Labels: backport-to-4.0.x, performance

#10913 Use local repository as tail in MavenExecutorTest
  impl/maven-executor/src/test/java/org/apache/maven/cling/executor/MavenExecutorTestSupport.java
Labels: skip-changelog

#10893 feat: enhance MultiThreadedBuilder with smart project scheduling
  impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/ConcurrencyDependencyGraph.java
  impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/MultiThreadedBuilder.java
  impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/SmartProjectComparator.java
  impl/maven-core/src/test/java/org/apache/maven/lifecycle/internal/builder/multithreaded/SmartProjectComparatorTest.java
Labels: enhancement

#10915 [maven-4.0.x] Fix mvnup tool issues #7934-#7938 (#9311)
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnup/ConsoleIcon.java
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnup/UpgradeContext.java
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnup/goals/AbstractUpgradeGoal.java
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnup/goals/InferenceStrategy.java
  impl/maven-cli/src/main/java/org/apache/maven/cling/invoker/mvnup/goals/ModelUpgradeStrategy.java
  impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvnup/ConsoleIconTest.java
  impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvnup/UpgradeContextTest.java
  impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvnup/goals/AbstractUpgradeGoalTest.java
  impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvnup/goals/InferenceStrategyTest.java
  impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvnup/goals/ModelUpgradeStrategyTest.java
  impl/maven-cli/src/test/java/org/apache/maven/cling/invoker/mvnup/goals/UpgradeWorkflowIntegrationTest.java
Labels: bug, backport, mvn40

#10916 [maven-4.0.x] Optimize XmlPlexusConfiguration for performance and thread safety (#2527)
  impl/maven-xml/BENCHMARKS.md
  impl/maven-xml/pom.xml
  impl/maven-xml/src/main/java/org/apache/maven/internal/xml/XmlPlexusConfiguration.java
  impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationBenchmark.java
  impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationConcurrencyBenchmark.java
  impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationMemoryBenchmark.java
  impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationOld.java
  impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlPlexusConfigurationTest.java
Labels: bug, backport, mvn40

#10917 [maven-4.0.x] Bug fix in the default directory computed by `DefaultSourceRoot`. (#10912)
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultSourceRootTest.java
Labels: bug, backport, mvn40

#10918 [maven-4.0.x] Refactor setupContainer to validate ExtensionContext, test class and instance, and throw clear IllegalStateExceptions (#10901, fixes #10428)
  impl/maven-testing/src/main/java/org/apache/maven/api/di/testing/MavenDIExtension.java
  impl/maven-testing/src/test/java/org/apache/maven/api/di/testing/SimpleDITest.java
Labels: bug, backport, mvn40

#2518 Optimize validation performance with lazy SourceHint evaluation
  compat/maven-model/pom.xml
  impl/maven-impl/pom.xml
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelValidator.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/model/ModelValidationBenchmark.java
  impl/maven-xml/pom.xml
  pom.xml
Labels: backport-to-4.0.x, performance

#10921 Add Maven version to error message when rejecting model versions
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelValidator.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/model/DefaultModelValidatorTest.java
Labels: enhancement

#10924 Rename single letter variables in DefaultModelValidator
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelValidator.java
Labels: maintenance, skip-changelog

#10903 Implement Injector.dispose() and add cleanup test
  impl/maven-di/src/main/java/org/apache/maven/di/Injector.java
  impl/maven-di/src/main/java/org/apache/maven/di/impl/InjectorImpl.java
  impl/maven-di/src/test/java/org/apache/maven/di/impl/InjectorImplTest.java
  impl/maven-testing/src/main/java/org/apache/maven/api/di/testing/MavenDIExtension.java
Labels: enhancement

#10923 Add PathMatcherFactory service with directory filtering optimization
  api/maven-api-core/src/main/java/org/apache/maven/api/services/PathMatcherFactory.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultPathMatcherFactory.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/PathSelector.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultPathMatcherFactoryTest.java
Labels: enhancement, backport-to-4.0.x

#2526 Optimize CompositeBeanHelper performance with comprehensive caching
  impl/maven-core/pom.xml
  impl/maven-core/src/main/java/org/apache/maven/configuration/internal/EnhancedCompositeBeanHelper.java
  impl/maven-core/src/main/java/org/apache/maven/configuration/internal/EnhancedConfigurationConverter.java
  impl/maven-core/src/test/java/org/apache/maven/configuration/internal/CompositeBeanHelperPerformanceTest.java
  impl/maven-core/src/test/java/org/apache/maven/configuration/internal/EnhancedCompositeBeanHelperTest.java
Labels: backport-to-4.0.x, performance

#2495 Expand value interning optimization and fix XML factory transformer usage
  api/maven-api-core/src/main/java/org/apache/maven/api/Constants.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultModelXmlFactory.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultPluginXmlFactory.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSettingsXmlFactory.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultToolchainsXmlFactory.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/XmlFactoryTransformerTest.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/model/InterningTransformerTest.java
  src/site/markdown/configuration.properties
  src/site/markdown/configuration.yaml
  src/site/markdown/maven-configuration.md
Labels: backport-to-4.0.x, performance

#10927 [maven-4.0.x] perf: optimize CompositeBeanHelper with reflection caching
  impl/maven-core/pom.xml
  impl/maven-core/src/main/java/org/apache/maven/configuration/internal/EnhancedCompositeBeanHelper.java
  impl/maven-core/src/main/java/org/apache/maven/configuration/internal/EnhancedConfigurationConverter.java
  impl/maven-core/src/test/java/org/apache/maven/configuration/internal/CompositeBeanHelperPerformanceTest.java
  impl/maven-core/src/test/java/org/apache/maven/configuration/internal/EnhancedCompositeBeanHelperTest.java
Labels: backport, performance, mvn40

#10935 Port the bug fixes identified when using that class in Maven clean and compiler plugin
  impl/maven-impl/src/main/java/org/apache/maven/impl/PathSelector.java
Labels: bug, backport-to-4.0.x

#10922 Remove unused core-it-support subprojects
  its/core-it-support/core-it-support-artifacts/pom.xml
  its/core-it-support/core-it-support-artifacts/src/main/assembly/repo.xml
  its/core-it-support/core-it-support-artifacts/src/main/repo/org/apache/maven/its/maven-core-it-support-old-location/1.1/maven-core-it-support-old-location-1.1.pom
  its/core-it-support/core-it-support-artifacts/src/main/repo/org/apache/maven/its/maven-core-it-support/1.0/maven-core-it-support-1.0.jar
  its/core-it-support/core-it-support-artifacts/src/main/repo/org/apache/maven/its/maven-core-it-support/1.0/maven-core-it-support-1.0.pom
  its/core-it-support/core-it-support-artifacts/src/main/repo/org/apache/maven/its/maven-core-it-support/1.1/maven-core-it-support-1.1.jar
  its/core-it-support/core-it-support-artifacts/src/main/repo/org/apache/maven/its/maven-core-it-support/1.1/maven-core-it-support-1.1.pom
  its/core-it-support/core-it-support-artifacts/src/main/repo/org/apache/maven/its/maven-core-it-support/1.2/maven-core-it-support-1.2-it.jar
  its/core-it-support/core-it-support-artifacts/src/main/repo/org/apache/maven/its/maven-core-it-support/1.2/maven-core-it-support-1.2.pom
  its/core-it-support/core-it-support-artifacts/src/main/repo/org/apache/maven/its/maven-core-it-support/1.3/maven-core-it-support-1.3.jar
  its/core-it-support/core-it-support-artifacts/src/main/repo/org/apache/maven/its/maven-core-it-support/1.3/maven-core-it-support-1.3.pom
  its/core-it-support/core-it-support-artifacts/src/main/repo/org/apache/maven/its/maven-core-it-support/1.4/maven-core-it-support-1.4.jar
  its/core-it-support/core-it-support-artifacts/src/main/repo/org/apache/maven/its/maven-core-it-support/1.4/maven-core-it-support-1.4.pom
  its/core-it-support/maven-it-sample-archetype/pom.xml
  its/core-it-support/maven-it-sample-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
  its/core-it-support/maven-it-sample-archetype/src/main/resources/META-INF/maven/archetype.xml
  its/core-it-support/maven-it-sample-archetype/src/main/resources/archetype-resources/out.txt
  its/core-it-support/maven-it-sample-archetype/src/main/resources/archetype-resources/pom.xml
  its/core-it-support/maven-it-sample-archetype/src/main/resources/archetype-resources/src/test/java/MavenITmngXXXXDescriptionOfProblemTest.java
  its/core-it-support/maven-it-sample-archetype/src/main/resources/archetype-resources/src/test/resources/mng-xxxx/checkstyle-assembly/pom.xml
  its/core-it-support/maven-it-sample-archetype/src/main/resources/archetype-resources/src/test/resources/mng-xxxx/checkstyle-assembly/src/main/resources/rule_set.xml
  its/core-it-support/maven-it-sample-archetype/src/main/resources/archetype-resources/src/test/resources/mng-xxxx/checkstyle-assembly/src/main/resources/stc_checks.xml
  its/core-it-support/maven-it-sample-archetype/src/main/resources/archetype-resources/src/test/resources/mng-xxxx/checkstyle-test/pom.xml
  its/core-it-support/maven-it-sample-archetype/src/main/resources/archetype-resources/src/test/resources/mng-xxxx/checkstyle-test/src/main/java/Class.java
  its/core-it-support/maven-it-sample-archetype/src/main/resources/archetype-resources/src/test/resources/mng-xxxx/pom.xml
  its/core-it-support/maven-it-sample-archetype/src/main/resources/archetype-resources/src/test/resources/mng-xxxx/readme.txt
  its/core-it-support/maven-it-sample/pom.xml
  its/core-it-support/maven-it-sample/src/test/java/org/apache/maven/it/MavenITmngXXXXDescriptionOfProblemTest.java
  its/core-it-support/maven-it-sample/src/test/resources/mng-xxxx/checkstyle-assembly/pom.xml
  its/core-it-support/maven-it-sample/src/test/resources/mng-xxxx/checkstyle-assembly/src/main/resources/rule_set.xml
  its/core-it-support/maven-it-sample/src/test/resources/mng-xxxx/checkstyle-assembly/src/main/resources/stc_checks.xml
  its/core-it-support/maven-it-sample/src/test/resources/mng-xxxx/checkstyle-test/pom.xml
  its/core-it-support/maven-it-sample/src/test/resources/mng-xxxx/checkstyle-test/src/main/java/Class.java
  its/core-it-support/maven-it-sample/src/test/resources/mng-xxxx/pom.xml
  its/core-it-support/maven-it-sample/src/test/resources/mng-xxxx/readme.txt
  its/core-it-support/pom.xml
Labels: skip-changelog

#10900 [MNG-8449] - Add Filtering Support to ProblemCollector
  api/maven-api-core/src/main/java/org/apache/maven/api/services/ProblemCollector.java
  compat/maven-builder-support/src/test/java/org/apache/maven/building/ProblemCollectorFactoryTest.java
Labels: enhancement

#10944 Add skipMavenRc to ExecutorRequest and use it in ITs
  impl/maven-executor/src/main/java/org/apache/maven/api/cli/ExecutorRequest.java
  impl/maven-executor/src/main/java/org/apache/maven/cling/executor/forked/ForkedMavenExecutor.java
  its/core-it-suite/pom.xml
  its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
  its/core-it-support/maven-it-helper/src/main/java/org/apache/maven/it/Verifier.java
Labels: enhancement, mvn40

#10947 [master] Fix XmlNode.equals returning false between two different node implementations (#10942)
  api/maven-api-xml/src/main/java/org/apache/maven/api/xml/XmlNode.java
  impl/maven-xml/src/main/java/org/apache/maven/internal/xml/XmlNodeImpl.java
  impl/maven-xml/src/test/java/org/apache/maven/internal/xml/XmlNodeImplTest.java
Labels: bug

#10958 Remove unused inner class
  compat/maven-builder-support/src/test/java/org/apache/maven/building/ProblemCollectorFactoryTest.java
Labels: maintenance, skip-changelog

#10961 Generating configuration documentation during site build
  apache-maven/pom.xml
  pom.xml
  src/configuration-templates/maven-configuration.md.vm
  src/site/markdown/configuration.properties
  src/site/markdown/configuration.yaml
  src/site/markdown/maven-configuration.md
Labels: maintenance

#10964 Add PathMatcherFactory.includesAll()
  api/maven-api-core/src/main/java/org/apache/maven/api/services/PathMatcherFactory.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultPathMatcherFactory.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/PathSelector.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultPathMatcherFactoryTest.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/PathSelectorTest.java
Labels: enhancement, backport-to-4.0.x

#10979 Generating configuration documentation during site build
  apache-maven/pom.xml
  pom.xml
  src/configuration-templates/maven-configuration.md.vm
  src/site/markdown/configuration.properties
  src/site/markdown/configuration.yaml
  src/site/markdown/maven-configuration.md
Labels: maintenance

#10990 Deprecate old project builder API in favor of new API
  impl/maven-core/src/main/java/org/apache/maven/project/DefaultDependencyResolutionRequest.java
  impl/maven-core/src/main/java/org/apache/maven/project/DefaultDependencyResolutionResult.java
  impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuilder.java
  impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuildingRequest.java
  impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectBuildingResult.java
  impl/maven-core/src/main/java/org/apache/maven/project/DefaultProjectDependenciesResolver.java
  impl/maven-core/src/main/java/org/apache/maven/project/DependencyResolutionException.java
  impl/maven-core/src/main/java/org/apache/maven/project/DependencyResolutionRequest.java
  impl/maven-core/src/main/java/org/apache/maven/project/DependencyResolutionResult.java
  impl/maven-core/src/main/java/org/apache/maven/project/ProjectBuilder.java
  impl/maven-core/src/main/java/org/apache/maven/project/ProjectBuildingException.java
  impl/maven-core/src/main/java/org/apache/maven/project/ProjectBuildingRequest.java
  impl/maven-core/src/main/java/org/apache/maven/project/ProjectBuildingResult.java
  impl/maven-core/src/main/java/org/apache/maven/project/ProjectDependenciesResolver.java
Labels: deprecated

#10945 Use Collections#isEmpty or String#isEmpty
  compat/maven-artifact/src/main/java/org/apache/maven/artifact/DefaultArtifact.java
  compat/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java
  compat/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/VersionRange.java
  compat/maven-builder-support/src/main/java/org/apache/maven/building/DefaultProblem.java
  compat/maven-compat/src/main/java/org/apache/maven/project/validation/ModelValidationResult.java
  compat/maven-compat/src/main/java/org/apache/maven/repository/metadata/ClasspathContainer.java
  compat/maven-compat/src/main/java/org/apache/maven/repository/metadata/DefaultClasspathTransformation.java
  compat/maven-compat/src/main/java/org/apache/maven/repository/metadata/DefaultGraphConflictResolver.java
  compat/maven-compat/src/main/java/org/apache/maven/repository/metadata/MetadataGraph.java
  compat/maven-compat/src/test/java/org/apache/maven/project/inheritance/t04/ProjectInheritanceTest.java
  compat/maven-compat/src/test/java/org/apache/maven/project/inheritance/t05/ProjectInheritanceTest.java
  compat/maven-compat/src/test/java/org/apache/maven/project/inheritance/t06/ProjectInheritanceTest.java
  compat/maven-compat/src/test/java/org/apache/maven/project/inheritance/t07/ProjectInheritanceTest.java
  compat/maven-compat/src/test/java/org/apache/maven/project/inheritance/t08/ProjectInheritanceTest.java
  compat/maven-compat/src/test/java/org/apache/maven/project/inheritance/t09/ProjectInheritanceTest.java
  compat/maven-compat/src/test/java/org/apache/maven/project/inheritance/t10/ProjectInheritanceTest.java
  compat/maven-embedder/src/main/java/org/apache/maven/cli/props/MavenProperties.java
  compat/maven-embedder/src/main/java/org/eclipse/sisu/plexus/PlexusXmlBeanConverter.java
  compat/maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelProblem.java
  compat/maven-model-builder/src/main/java/org/apache/maven/model/building/ModelBuildingException.java
  compat/maven-model-builder/src/main/java/org/apache/maven/model/building/ModelProblemUtils.java
  compat/maven-model-builder/src/main/java/org/apache/maven/model/inheritance/DefaultInheritanceAssembler.java
  compat/maven-model-builder/src/main/java/org/apache/maven/model/interpolation/ProblemDetectingValueSource.java
  compat/maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java
  compat/maven-settings-builder/src/main/java/org/apache/maven/settings/building/DefaultSettingsBuilder.java
  compat/maven-settings-builder/src/main/java/org/apache/maven/settings/building/DefaultSettingsProblem.java
  compat/maven-settings-builder/src/main/java/org/apache/maven/settings/validation/DefaultSettingsValidator.java
  impl/maven-cli/src/main/java/org/apache/maven/cling/props/MavenProperties.java
  impl/maven-core/src/main/java/org/apache/maven/RepositoryUtils.java
  impl/maven-core/src/main/java/org/apache/maven/internal/MultilineMessageHelper.java
  impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/ConcurrencyDependencyGraph.java
  impl/maven-core/src/main/java/org/apache/maven/plugin/PluginParameterException.java
  impl/maven-core/src/test/java/org/apache/maven/artifact/handler/ArtifactHandlerTest.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSettingsValidator.java
Labels: maintenance

#10959 Improvements in ITs - executing by mvn verify
  .github/workflows/maven.yml
  its/core-it-suite/pom.xml
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng5669ReadPomsOnce.java
  its/pom.xml
  pom.xml
Labels: enhancement

#10969 Avoid parsing MAVEN_OPTS (3.9.x)
  apache-maven/src/bin/mvn.cmd
Labels: bug, mvn3

#10970 Avoid parsing MAVEN_OPTS (master/4.x)
  apache-maven/src/assembly/maven/bin/mvn
  apache-maven/src/assembly/maven/bin/mvn.cmd
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh10937QuotedPipesInMavenOptsTest.java
  its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
  its/core-it-suite/src/test/resources/gh-10937-pipes-maven-opts/.mvn/jvm.config
  its/core-it-suite/src/test/resources/gh-10937-pipes-maven-opts/pom.xml
Labels: bug, backport-to-4.0.x

#10936 [maven-4.0.x] Port the bug fixes identified when using that class in Maven clean and compiler plugin (#10935)
  impl/maven-impl/src/main/java/org/apache/maven/impl/PathSelector.java
Labels: bug, backport, mvn40

#10998 Fix maven.mainClass property missing for external tools
  apache-maven/src/assembly/maven/bin/m2.conf
Labels: bug, backport-to-4.0.x

#11008 Backport of "Add PathMatcherFactory.includesAll()"
  api/maven-api-core/src/main/java/org/apache/maven/api/services/PathMatcherFactory.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultPathMatcherFactory.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
  impl/maven-impl/src/main/java/org/apache/maven/impl/PathSelector.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultPathMatcherFactoryTest.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/PathSelectorTest.java
Labels: enhancement, backport, mvn40
