Repository apache/maven, pull requests merged in 2025-09, with the labels that each got.

#11083 Bug: bad cache isolation between two sessions
  compat/maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java
Labels: bug

#10931 Move InputLocation/InputLocationTracker/InputSource to velocity templates
  api/maven-api-model/pom.xml
  api/maven-api-model/src/main/java/org/apache/maven/api/model/InputLocation.java
  api/maven-api-model/src/main/java/org/apache/maven/api/model/InputLocationTracker.java
  api/maven-api-model/src/main/java/org/apache/maven/api/model/InputSource.java
  src/mdo/java/InputLocation.java
  src/mdo/java/InputLocationTracker.java
  src/mdo/java/InputSource.java
Labels: maintenance

#11129 Fix #11127: enforce non-null keys for InputLocation lookups and document behavior (master)
  src/mdo/java/InputLocation.java
  src/mdo/java/InputLocationTracker.java
  src/mdo/model.vm
Labels: bug

#11101 fix: include extension in equals/hashCode of DefaultArtifactCoordinates
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultArtifactCoordinates.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultArtifactCoordinatesTest.java
Labels: bug, backport-to-4.0.x

#11124 Fix subproject discovery kicking in too often
  impl/maven-core/src/test/java/org/apache/maven/project/DefaultMavenProjectBuilderTest.java
  impl/maven-core/src/test/resources/projects/modules-empty/child/pom.xml
  impl/maven-core/src/test/resources/projects/modules-empty/pom.xml
  impl/maven-core/src/test/resources/projects/subprojects-empty/child/pom.xml
  impl/maven-core/src/test/resources/projects/subprojects-empty/pom.xml
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
Labels: bug, backport-to-4.0.x

#11130 Add missing equals and hashCode methods in modular Java path type.
  api/maven-api-core/src/main/java/org/apache/maven/api/JavaPathType.java
Labels: bug, backport, mvn40

#11105 Improve source root modification warning message
  maven-core/src/main/java/org/apache/maven/project/MavenProject.java
Labels: mvn3

#11132 [maven-4.0.x] model-builder: simplify subproject auto-discovery decision (#11124)
  impl/maven-core/src/test/java/org/apache/maven/project/DefaultMavenProjectBuilderTest.java
  impl/maven-core/src/test/resources/projects/modules-empty/child/pom.xml
  impl/maven-core/src/test/resources/projects/modules-empty/pom.xml
  impl/maven-core/src/test/resources/projects/subprojects-empty/child/pom.xml
  impl/maven-core/src/test/resources/projects/subprojects-empty/pom.xml
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
Labels: bug, backport, mvn40

#11150 IT fixes
  its/core-it-suite/pom.xml
Labels: maintenance

#11138 GH-10210: fix too eager decrypt of legacy passwords
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSettingsBuilder.java
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh10210SettingsXmlDecryptTest.java
  its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
  its/core-it-suite/src/test/resources/gh-10210-settings-xml-decrypt/HOME/.m2/settings-security.xml
  its/core-it-suite/src/test/resources/gh-10210-settings-xml-decrypt/pom.xml
  its/core-it-suite/src/test/resources/gh-10210-settings-xml-decrypt/settings-fails.xml
  its/core-it-suite/src/test/resources/gh-10210-settings-xml-decrypt/settings-passes.xml
  its/core-it-suite/src/test/resources/gh-10210-settings-xml-decrypt/src/main/resources/file.properties
Labels: bug, backport-to-4.0.x

#11163 Consumer POM should keep only transitive dependencies, fixes #11162
  impl/maven-core/src/main/java/org/apache/maven/internal/transformation/impl/DefaultConsumerPomBuilder.java
  its/.gitignore
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITgh11162ConsumerPomScopesTest.java
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8527ConsumerPomTest.java
  its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/app/pom.xml
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/pom.xml
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/compile-dep/1.0/compile-dep-1.0.jar
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/compile-dep/1.0/compile-dep-1.0.pom
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/compile-only-dep/1.0/compile-only-dep-1.0.jar
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/compile-only-dep/1.0/compile-only-dep-1.0.pom
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/runtime-dep/1.0/runtime-dep-1.0.jar
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/runtime-dep/1.0/runtime-dep-1.0.pom
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/test-dep/1.0/test-dep-1.0.jar
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/test-dep/1.0/test-dep-1.0.pom
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/test-only-dep/1.0/test-only-dep-1.0.jar
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/test-only-dep/1.0/test-only-dep-1.0.pom
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/test-runtime-dep/1.0/test-runtime-dep-1.0.jar
  its/core-it-suite/src/test/resources/gh-11162-consumer-pom-scopes/repo/org/apache/maven/its/gh11162/test-runtime-dep/1.0/test-runtime-dep-1.0.pom
  its/core-it-suite/src/test/resources/mng-6957-buildconsumer/expected/simple-weather.pom
Labels: bug, backport-to-4.0.x
