Repository apache/maven, pull requests merged in 2025-05, with the labels that each got.

#2279 [MNG-8712] dependency version is a requirement, not effective
  maven-model/src/main/mdo/maven.mdo
Labels: mvn3

#2295 [MNG-8717] Remove maven-plugin-plugin:addPluginArtifactMetadata from default binding
  maven-core/src/main/resources/META-INF/plexus/default-bindings.xml
  maven-core/src/test/java/org/apache/maven/lifecycle/LifecycleExecutorTest.java
Labels: mvn3

#2296 [MNG-8169] Add opens java.base/java.lang=ALL-UNNAMED for MinGW
  apache-maven/src/bin/mvn
Labels: mvn3

#2297 [MNG-8722] Use a single standalone version of asm
  apache-maven/src/main/appended-resources/licenses/unrecognized-asm-9.8.txt
  maven-core/pom.xml
  maven-embedder/pom.xml
  maven-model-builder/pom.xml
  maven-resolver-provider/pom.xml
  pom.xml
Labels: mvn3

#2282 [MNG-8716] Bump resolver to 1.9.23
  pom.xml
Labels: dependencies, mvn3

#2274 [MNG-8572] Support DI beans in build extensions
  impl/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultTypeRegistry.java
  impl/maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8525MavenDIPlugin.java
  its/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng8572DITypeHandlerTest.java
  its/core-it-suite/src/test/java/org/apache/maven/it/TestSuiteOrdering.java
  its/core-it-suite/src/test/resources/mng-8525-maven-di-plugin/pom.xml
  its/core-it-suite/src/test/resources/mng-8572-di-type-handler/README.md
  its/core-it-suite/src/test/resources/mng-8572-di-type-handler/extension/pom.xml
  its/core-it-suite/src/test/resources/mng-8572-di-type-handler/extension/src/main/java/org/apache/maven/its/mng8572/extension/CustomType.java
  its/core-it-suite/src/test/resources/mng-8572-di-type-handler/extension/src/main/java/org/apache/maven/its/mng8572/extension/CustomTypeProvider.java
  its/core-it-suite/src/test/resources/mng-8572-di-type-handler/extension/src/main/java/org/apache/maven/its/mng8572/extension/NoOpMojo.java
  its/core-it-suite/src/test/resources/mng-8572-di-type-handler/test/dummy-artifact-pom.xml
  its/core-it-suite/src/test/resources/mng-8572-di-type-handler/test/pom.xml
  its/core-it-suite/src/test/resources/mng-8572-di-type-handler/test/settings.xml
  its/core-it-suite/src/test/resources/mng-8572-di-type-handler/test/src/main/java/org/apache/maven/its/mng8572/test/DummyClass.java
Labels: enhancement

#2312 [MNG-8729] Use correct `outputStream` destination; `request` instead of `path` in `DefaultPluginXmlFactory#write`
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultPluginXmlFactory.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultPluginXmlFactoryTest.java
Labels: bug

#2341 [MNG-8731] Use https for xsi:schemaLocation in generated descriptors
  api/maven-api-cli/src/main/mdo/core-extensions.mdo
  api/maven-api-plugin/src/main/mdo/lifecycle.mdo
  api/maven-api-settings/src/main/mdo/settings.mdo
  api/maven-api-toolchain/src/main/mdo/toolchains.mdo
Labels: documentation

#2343 [MNG-8731] Use https for xsi:schemaLocation in generated descriptors
  maven-core/src/main/mdo/extension.mdo
  maven-core/src/main/mdo/toolchains.mdo
  maven-embedder/src/main/mdo/core-extensions.mdo
  maven-plugin-api/src/main/mdo/lifecycle.mdo
  maven-plugin-api/src/main/mdo/plugin.mdo
  maven-repository-metadata/src/main/mdo/metadata.mdo
  maven-settings/src/main/mdo/settings.mdo
Labels: mvn3, documentation

#2345 [MNG-8711] Fix concurrent cache access
  maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleDependencyResolver.java
  maven-core/src/main/java/org/apache/maven/plugin/DefaultPluginDescriptorCache.java
  maven-core/src/main/java/org/apache/maven/project/artifact/DefaultProjectArtifactsCache.java
Labels: bug, mvn3

#2353 Update README.md
  README.md
Labels: mvn3, documentation

#2393 [MNG-8396] Backport: add cache layer to the filtered dep graph
  maven-core/src/main/java/org/apache/maven/graph/FilteredProjectDependencyGraph.java
Labels: mvn3

#2412 [MNG-8761] Add Maven 3 MavenToolchainsXpp3Reader/Writer
  compat/maven-toolchain-model/pom.xml
  compat/maven-toolchain-model/src/main/java/org/apache/maven/toolchain/model/io/xpp3/MavenToolchainsXpp3Reader.java
  compat/maven-toolchain-model/src/main/java/org/apache/maven/toolchain/model/io/xpp3/MavenToolchainsXpp3Writer.java
Labels: bug
