Repository apache/maven, pull requests merged in 2025-08, with the labels that each got.

#11007 [maven-4.0.x] Fix maven.mainClass property missing for external tools (#10998)
  apache-maven/src/assembly/maven/bin/m2.conf
Labels: bug, backport, mvn40

#10997 Fix recursive update issue in SmartProjectComparator
  impl/maven-core/src/main/java/org/apache/maven/lifecycle/internal/builder/multithreaded/SmartProjectComparator.java
  impl/maven-core/src/test/java/org/apache/maven/lifecycle/internal/builder/multithreaded/SmartProjectComparatorTest.java
Labels: bug

#11038 Allow single build per branch or pull request
  .github/workflows/maven.yml
Labels: build

#11039 Uninterpolated repositories from parent POMs during model building (backport)
  impl/maven-impl/src/main/java/org/apache/maven/impl/model/DefaultModelBuilder.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/model/DefaultModelBuilderTest.java
Labels: backport-to-4.0.x

#11047 Add standard github_actions label for dependabot in branches
  .github/dependabot.yml
Labels: maintenance, skip-changelog

#11045 Allow single build per branch or pull request
  .github/workflows/maven.yml
Labels: build

#11073 Simplify prefix resolution (#11072)
  impl/maven-core/src/main/java/org/apache/maven/plugin/prefix/internal/DefaultPluginPrefixResolver.java
Labels: enhancement, backport, performance, mvn40

#11049 [#11048] Fix race condition in MessageUtils
  impl/maven-jline/src/main/java/org/apache/maven/jline/MessageUtils.java
Labels: bug, backport-to-4.0.x

#11078 [maven-4.0.x] Fix XMLReader#getURL and enable the unit test (#11069)
  api/maven-api-core/src/main/java/org/apache/maven/api/services/xml/XmlReaderRequest.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultPluginXmlFactoryTest.java
Labels: bug, backport, mvn40

#11080 [maven-4.0.x] Fix targetPath parameter ignored in resource bundles (fixes #11062) (#11063)
  impl/maven-core/src/main/java/org/apache/maven/project/ConnectedResource.java
  impl/maven-core/src/main/java/org/apache/maven/project/MavenProject.java
  impl/maven-core/src/test/java/org/apache/maven/project/PomConstructionTest.java
  impl/maven-core/src/test/java/org/apache/maven/project/ResourceIncludeTest.java
  impl/maven-core/src/test/resources-project-builder/target-path-regression/pom.xml
  impl/maven-impl/src/main/java/org/apache/maven/impl/DefaultSourceRoot.java
  impl/maven-impl/src/test/java/org/apache/maven/impl/DefaultSourceRootTest.java
Labels: bug, backport, mvn40

#11068 Enable prevent branch protection rules
  .asf.yaml
Labels: maintenance
